- name: Repoblar ACR con imagenes
  hosts: localhost
  gather_facts: false
  roles:
    - acr

- name: Configurar VM y desplegar web con Podman
  hosts: vm
  gather_facts: false
  roles:
    - vm